/*
 * GUI.java
 *
 * Created on __DATE__, __TIME__
 */

package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import javax.swing.AbstractAction;
import javax.swing.JFileChooser;
import javax.swing.JTextPane;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.UndoManager;

import DataStyle.Records;

/**
 *
 * @author  __USER__
 */
public class GUI extends javax.swing.JFrame {

	/** Creates new form GUI */
	public GUI() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jToolBar1 = new javax.swing.JToolBar();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jToolBar2 = new javax.swing.JToolBar();
		jButton5 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		jToolBar3 = new javax.swing.JToolBar();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jToolBar4 = new javax.swing.JToolBar();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTree1 = new javax.swing.JTree();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextPane1 = new javax.swing.JTextPane();
		jTabbedPane2 = new javax.swing.JTabbedPane();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTextPane3 = new javax.swing.JTextPane();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTextPane4 = new javax.swing.JTextPane();
		jMenuBar4 = new javax.swing.JMenuBar();
		jMenu21 = new javax.swing.JMenu();
		jMenuItem81 = new javax.swing.JMenuItem();
		jMenuItem82 = new javax.swing.JMenuItem();
		jMenuItem83 = new javax.swing.JMenuItem();
		jMenuItem84 = new javax.swing.JMenuItem();
		jSeparator17 = new javax.swing.JSeparator();
		jMenuItem85 = new javax.swing.JMenuItem();
		jMenu22 = new javax.swing.JMenu();
		jMenuItem86 = new javax.swing.JMenuItem();
		jMenuItem87 = new javax.swing.JMenuItem();
		jSeparator18 = new javax.swing.JSeparator();
		jMenuItem88 = new javax.swing.JMenuItem();
		jMenuItem89 = new javax.swing.JMenuItem();
		jMenuItem90 = new javax.swing.JMenuItem();
		jMenuItem91 = new javax.swing.JMenuItem();
		jSeparator19 = new javax.swing.JSeparator();
		jMenuItem92 = new javax.swing.JMenuItem();
		jMenu23 = new javax.swing.JMenu();
		jMenuItem93 = new javax.swing.JMenuItem();
		jMenuItem94 = new javax.swing.JMenuItem();
		jMenuItem95 = new javax.swing.JMenuItem();
		jMenuItem96 = new javax.swing.JMenuItem();
		jMenu24 = new javax.swing.JMenu();
		jMenuItem97 = new javax.swing.JMenuItem();
		jMenuItem98 = new javax.swing.JMenuItem();
		jMenu25 = new javax.swing.JMenu();
		jMenuItem99 = new javax.swing.JMenuItem();
		jSeparator20 = new javax.swing.JSeparator();
		jMenuItem100 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("DBMS");

		jToolBar1.setFloatable(false);
		jToolBar1.setRollover(true);

		jButton3.setIcon(new javax.swing.ImageIcon(
				"icons\\tiny_new_script.png")); // NOI18N
		jButton3.setToolTipText("New SQL file...");
		jButton3.setFocusable(false);
		jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton3);

		jButton4.setIcon(new javax.swing.ImageIcon(
				"icons\\tiny_loadsql.png")); // NOI18N
		jButton4.setToolTipText("Open Existed SQL file...");
		jButton4.setFocusable(false);
		jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton4);

		jButton2.setIcon(new javax.swing.ImageIcon(
				"icons\\tiny_savesql.png")); // NOI18N
		jButton2.setToolTipText("Save Current Query to File...");
		jButton2.setFocusable(false);
		jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton2);

		jToolBar2.setFloatable(false);
		jToolBar2.setRollover(true);

		jButton5.setIcon(new javax.swing.ImageIcon(
				"icons\\tiny_execute.png")); // NOI18N
		jButton5.setToolTipText("Excute Query File.");
		jButton5.setFocusable(false);
		jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jToolBar2.add(jButton5);

		jButton1.setIcon(new javax.swing.ImageIcon(
				"icons\\tiny_execute_current.png")); // NOI18N
		jButton1.setToolTipText("Excute Current Line.");
		jButton1.setFocusable(false);
		jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jToolBar2.add(jButton1);
		jButton1.getAccessibleContext().setAccessibleDescription("");

		jToolBar3.setFloatable(false);
		jToolBar3.setRollover(true);
		jToolBar3.setMaximumSize(new java.awt.Dimension(105, 27));
		jToolBar3.setMinimumSize(new java.awt.Dimension(105, 27));

		jButton6.setIcon(new javax.swing.ImageIcon(
				"icons\\cut_edit.gif")); // NOI18N
		jButton6.setToolTipText("Cut Selected.");
		jButton6.setFocusable(false);
		jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		jToolBar3.add(jButton6);

		jButton7.setIcon(new javax.swing.ImageIcon(
				"icons\\copy_edit.gif")); // NOI18N
		jButton7.setToolTipText("Copy Selected.");
		jButton7.setFocusable(false);
		jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});
		jToolBar3.add(jButton7);

		jButton8.setIcon(new javax.swing.ImageIcon(
				"icons\\paste_edit.gif")); // NOI18N
		jButton8.setToolTipText("Paste.");
		jButton8.setFocusable(false);
		jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});
		jToolBar3.add(jButton8);

		jButton9.setIcon(new javax.swing.ImageIcon(
				"icons\\delete_edit.gif")); // NOI18N
		jButton9.setToolTipText("Delete Selected.");
		jButton9.setFocusable(false);
		jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});
		jToolBar3.add(jButton9);

		jToolBar4.setFloatable(false);

		jButton10.setIcon(new javax.swing.ImageIcon(
				"icons\\tiny_undo.png")); // NOI18N
		jButton10.setToolTipText("Undo");
		jButton10.setFocusable(false);
		jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton10ActionPerformed(evt);
			}
		});
		jToolBar4.add(jButton10);

		jButton11.setIcon(new javax.swing.ImageIcon(
				"icons\\tiny_redo.png")); // NOI18N
		jButton11.setToolTipText("Redo.");
		jButton11.setFocusable(false);
		jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});
		jToolBar4.add(jButton11);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Browser"));

		jTree1.setAutoscrolls(true);
		jTree1.setFocusCycleRoot(true);
		jScrollPane1.setViewportView(jTree1);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403,
				Short.MAX_VALUE));

		jTabbedPane1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Query Window"));
		jTabbedPane1
				.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

		jTextPane1.setFont(new java.awt.Font("Courier New", 0, 12));
		jTextPane1.getDocument().addUndoableEditListener(new UndoableEditListener() {
		    public void undoableEditHappened(UndoableEditEvent evt) {
		        undoManager.addEdit(evt.getEdit());
		    }
		});
		jScrollPane2.setViewportView(jTextPane1);

		jTabbedPane1.addTab("Query 1", jScrollPane2);

		jTabbedPane2.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Output Windows"));
		jTabbedPane2
				.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

		jTextPane3.setFont(new java.awt.Font("Courier New", 0, 12));
		jTextPane3.getDocument().addUndoableEditListener(new UndoableEditListener() {
		    public void undoableEditHappened(UndoableEditEvent evt) {
		        undoManager.addEdit(evt.getEdit());
		    }
		});
		jScrollPane4.setViewportView(jTextPane3);

		jTabbedPane2.addTab("Output", jScrollPane4);

		jTextPane4.setFont(new java.awt.Font("Courier New", 0, 12));
		jTextPane4.getDocument().addUndoableEditListener(new UndoableEditListener() {
		    public void undoableEditHappened(UndoableEditEvent evt) {
		        undoManager.addEdit(evt.getEdit());
		    }
		});
		jScrollPane5.setViewportView(jTextPane4);

		jTabbedPane2.addTab("Result 1", jScrollPane5);

		jMenu21.setText("File");

		jMenuItem81.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_N,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem81.setIcon(new javax.swing.ImageIcon(
				"icons\\tiny_new_script.png")); // NOI18N
		jMenuItem81.setText("New Query");
		jMenuItem81.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem81ActionPerformed(evt);
			}
		});
		jMenu21.add(jMenuItem81);

		jMenuItem82.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_O,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem82.setIcon(new javax.swing.ImageIcon(
				"icons\\tiny_loadsql.png")); // NOI18N
		jMenuItem82.setText("Open Query");
		jMenuItem82.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem82ActionPerformed(evt);
			}
		});
		jMenu21.add(jMenuItem82);

		jMenuItem83.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_S,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem83.setIcon(new javax.swing.ImageIcon(
				"icons\\tiny_savesql.png")); // NOI18N
		jMenuItem83.setText("Save Query");
		jMenuItem83.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem83ActionPerformed(evt);
			}
		});
		jMenu21.add(jMenuItem83);

		jMenuItem84.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_S,
				java.awt.event.InputEvent.SHIFT_MASK
						| java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem84.setIcon(new javax.swing.ImageIcon(
				"icons\\tiny_saveas.png")); // NOI18N
		jMenuItem84.setText("Save As...");
		jMenuItem84.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem84ActionPerformed(evt);
			}
		});
		jMenu21.add(jMenuItem84);
		jMenu21.add(jSeparator17);

		jMenuItem85.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_Q,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem85.setText("Exit");
		jMenuItem85.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem85ActionPerformed(evt);
			}
		});
		jMenu21.add(jMenuItem85);

		jMenuBar4.add(jMenu21);

		jMenu22.setText("Edit");

		jMenuItem86.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_Z,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem86.setIcon(new javax.swing.ImageIcon(
				"icons\\tiny_undo.png")); // NOI18N
		jMenuItem86.setText("Undo");
		jMenuItem86.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem86ActionPerformed(evt);
			}
		});
		jMenu22.add(jMenuItem86);

		jMenuItem87.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_Y,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem87.setIcon(new javax.swing.ImageIcon(
				"icons\\tiny_redo.png")); // NOI18N
		jMenuItem87.setText("Redo");
		jMenuItem87.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem87ActionPerformed(evt);
			}
		});
		jMenu22.add(jMenuItem87);
		jMenu22.add(jSeparator18);

		jMenuItem88.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_X,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem88.setIcon(new javax.swing.ImageIcon(
				"icons\\cut_edit.gif")); // NOI18N
		jMenuItem88.setText("Cut");
		jMenuItem88.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem88ActionPerformed(evt);
			}
		});
		jMenu22.add(jMenuItem88);

		jMenuItem89.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_C,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem89.setIcon(new javax.swing.ImageIcon(
				"icons\\copy_edit.gif")); // NOI18N
		jMenuItem89.setText("Copy");
		jMenuItem89.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem89ActionPerformed(evt);
			}
		});
		jMenu22.add(jMenuItem89);

		jMenuItem90.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_V,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem90.setIcon(new javax.swing.ImageIcon(
				"icons\\paste_edit.gif")); // NOI18N
		jMenuItem90.setText("Paste");
		jMenuItem90.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem90ActionPerformed(evt);
			}
		});
		jMenu22.add(jMenuItem90);

		jMenuItem91.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_DELETE,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem91.setIcon(new javax.swing.ImageIcon(
				"icons\\delete_edit.gif")); // NOI18N
		jMenuItem91.setText("Delete");
		jMenuItem91.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem91ActionPerformed(evt);
			}
		});
		jMenu22.add(jMenuItem91);
		jMenu22.add(jSeparator19);

		jMenuItem92.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_A,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem92.setText("Select All");
		jMenuItem92.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem92ActionPerformed(evt);
			}
		});
		jMenu22.add(jMenuItem92);

		jMenuBar4.add(jMenu22);

		jMenu23.setText("Query");

		jMenuItem93.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_ENTER,
				java.awt.event.InputEvent.SHIFT_MASK
						| java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem93.setIcon(new javax.swing.ImageIcon(
				"icons\\tiny_execute.png")); // NOI18N
		jMenuItem93.setText("Excute All");
		jMenuItem93.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem93ActionPerformed(evt);
			}
		});
		jMenu23.add(jMenuItem93);

		jMenuItem94.setText("Excute All to Text");
		jMenuItem94.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem94ActionPerformed(evt);
			}
		});
		jMenu23.add(jMenuItem94);

		jMenuItem95.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_ENTER,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem95
				.setIcon(new javax.swing.ImageIcon(
						"icons\\tiny_execute_current.png")); // NOI18N
		jMenuItem95.setText("Excute Current Line");
		jMenuItem95.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem95ActionPerformed(evt);
			}
		});
		jMenu23.add(jMenuItem95);

		jMenuItem96.setText("Excute Current Line to Text");
		jMenuItem96.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem96ActionPerformed(evt);
			}
		});
		jMenu23.add(jMenuItem96);

		jMenuBar4.add(jMenu23);

		jMenu24.setText("Database");

		jMenuItem97.setText("New Database");
		jMenuItem97.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem97ActionPerformed(evt);
			}
		});
		jMenu24.add(jMenuItem97);

		jMenuItem98.setText("Manage Database");
		jMenuItem98.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem98ActionPerformed(evt);
			}
		});
		jMenu24.add(jMenuItem98);

		jMenuBar4.add(jMenu24);

		jMenu25.setText("Help");

		jMenuItem99.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_F1, 0));
		jMenuItem99.setText("Help");
		jMenuItem99.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem99ActionPerformed(evt);
			}
		});
		jMenu25.add(jMenuItem99);
		jMenu25.add(jSeparator20);

		jMenuItem100.setText("About This DBMS");
		jMenuItem100.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem100ActionPerformed(evt);
			}
		});
		jMenu25.add(jMenuItem100);

		jMenuBar4.add(jMenu25);

		setJMenuBar(jMenuBar4);
		
		jButton10.setEnabled(false);
		jButton11.setEnabled(false);
		jMenuItem86.setEnabled(false);
		jMenuItem87.setEnabled(false);
		RefreshTree();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jToolBar1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jToolBar4,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jToolBar3,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jToolBar2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jPanel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jTabbedPane2,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						430,
																						Short.MAX_VALUE)
																				.addComponent(
																						jTabbedPane1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						430,
																						Short.MAX_VALUE))))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jToolBar1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jToolBar4,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jToolBar3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jToolBar2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jTabbedPane1,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		214,
																		Short.MAX_VALUE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jTabbedPane2,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		211,
																		Short.MAX_VALUE))
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jMenuItem100ActionPerformed(java.awt.event.ActionEvent evt) {
		Message message = new Message("Statement",
				"Author:	  Kiki Zhang, Magma Yan, Qifeng Zhu");
		message.setVisible(true);
	}

	private void jMenuItem99ActionPerformed(java.awt.event.ActionEvent evt) {
		Message message = new Message("Help",
				"All sql statements accords to SQL 97'");
		message.setVisible(true);
	}

	private void jMenuItem98ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO Manage Database
	}

	private void jMenuItem97ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO New Database
	}

	private void jMenuItem96ActionPerformed(java.awt.event.ActionEvent evt) {
		jButton1ActionPerformed(evt);
	}

	private void jMenuItem95ActionPerformed(java.awt.event.ActionEvent evt) {
		jButton1ActionPerformed(evt);
	}

	private void jMenuItem94ActionPerformed(java.awt.event.ActionEvent evt) {
		javax.swing.JScrollPane javax = (javax.swing.JScrollPane) jTabbedPane1.getSelectedComponent();
		javax.swing.JTextPane textpane = (javax.swing.JTextPane) javax.getViewport().getView();
		String text = textpane.getText();
		ArrayList<Records> records = Main.main.excutePlan(text);
		String result = "";
		for (int i = 0; i < records.size(); i++) {
			if (records.get(i) != null)
				result += records.get(i).toString();
			result += "******************************************\r\n";
		}
		if (!result.equals("")) {
			jTextPane3.setText(result);
			jTabbedPane2.setSelectedIndex(0);
		}
	}

	private void jMenuItem93ActionPerformed(java.awt.event.ActionEvent evt) {
		jButton5ActionPerformed(evt);
	}

	private void jMenuItem92ActionPerformed(java.awt.event.ActionEvent evt) {
		javax.swing.JScrollPane javax = (javax.swing.JScrollPane) jTabbedPane1
				.getSelectedComponent();
		javax.swing.JTextPane textpane = (javax.swing.JTextPane) javax
				.getViewport().getView();
		textpane.setSelectionStart(0);
		textpane.setSelectionEnd(textpane.getText().length());
	}

	private void jMenuItem91ActionPerformed(java.awt.event.ActionEvent evt) {
		jButton9ActionPerformed(evt);
	}

	private void jMenuItem90ActionPerformed(java.awt.event.ActionEvent evt) {
		jButton8ActionPerformed(evt);
	}

	private void jMenuItem89ActionPerformed(java.awt.event.ActionEvent evt) {
		jButton7ActionPerformed(evt);
	}

	private void jMenuItem88ActionPerformed(java.awt.event.ActionEvent evt) {
		jButton6ActionPerformed(evt);
	}

	private void jMenuItem87ActionPerformed(java.awt.event.ActionEvent evt) {
		jButton11ActionPerformed(evt);
	}

	private void jMenuItem86ActionPerformed(java.awt.event.ActionEvent evt) {
		jButton10ActionPerformed(evt);
	}

	private void jMenuItem85ActionPerformed(java.awt.event.ActionEvent evt) {
		System.exit(0);
	}

	private void jMenuItem84ActionPerformed(java.awt.event.ActionEvent evt) {
		// Save as...
		javax.swing.JScrollPane javax = (javax.swing.JScrollPane) jTabbedPane1
				.getSelectedComponent();
		javax.swing.JTextPane textpane = (javax.swing.JTextPane) javax
				.getViewport().getView();
		String text = textpane.getText();
		if (text.equals("")) {
			Message message = new Message("Error", "Empty file!");
			message.setVisible(true);
			return;
		}
		JFileChooser fileChooser = new JFileChooser();
		FileNameExtensionFilter filter = new FileNameExtensionFilter(
				"SQL file", "sql");
		FileNameExtensionFilter filter1 = new FileNameExtensionFilter(
				"Text file", "txt");
		fileChooser.setFileFilter(filter1);
		fileChooser.setFileFilter(filter);
		fileChooser.setMultiSelectionEnabled(false);
		int ret = fileChooser.showSaveDialog(jButton2);
		if (ret == JFileChooser.APPROVE_OPTION) {
			String name = fileChooser.getSelectedFile().getName();
			String path = fileChooser.getSelectedFile().getAbsolutePath();
			if (!name.toLowerCase().endsWith(".sql")
					&& !name.toLowerCase().endsWith(".txt")) {
				name += ".sql";
				path += ".sql";
			}
			if (saveFile(path, text) == 1) {
				filenameMap.put(textpane, path);
				jTabbedPane1.setTitleAt(jTabbedPane1.getSelectedIndex(), name);
			} else {
				Message a = new Message("Error",
						"Error occurred when saving file!");
				a.setVisible(true);
			}
		}
	}

	private void jMenuItem83ActionPerformed(java.awt.event.ActionEvent evt) {
		jButton2ActionPerformed(evt);
	}

	private void jMenuItem82ActionPerformed(java.awt.event.ActionEvent evt) {
		jButton4ActionPerformed(evt);
	}

	private void jMenuItem81ActionPerformed(java.awt.event.ActionEvent evt) {
		jButton3ActionPerformed(evt);
	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		// Delete button
		javax.swing.JScrollPane javax = (javax.swing.JScrollPane) jTabbedPane1
				.getSelectedComponent();
		javax.swing.JTextPane textpane = (javax.swing.JTextPane) javax
				.getViewport().getView();
		int start = textpane.getSelectionStart();
		int end = textpane.getSelectionEnd();
		if (start != end) {
			textpane.setText(textpane.getText().substring(0, start)
					+ textpane.getText().substring(end));
			textpane.setSelectionStart(start);
			textpane.setSelectionEnd(start);
		}
	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		javax.swing.JScrollPane javax = (javax.swing.JScrollPane) jTabbedPane1
				.getSelectedComponent();
		javax.swing.JTextPane textpane = (javax.swing.JTextPane) javax
				.getViewport().getView();
		textpane.paste();
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		javax.swing.JScrollPane javax = (javax.swing.JScrollPane) jTabbedPane1
				.getSelectedComponent();
		javax.swing.JTextPane textpane = (javax.swing.JTextPane) javax
				.getViewport().getView();
		textpane.copy();
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		javax.swing.JScrollPane javax = (javax.swing.JScrollPane) jTabbedPane1
				.getSelectedComponent();
		javax.swing.JTextPane textpane = (javax.swing.JTextPane) javax
				.getViewport().getView();
		textpane.cut();
	}

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			undoManager.redo();
		} catch (CannotRedoException cre) {
			cre.printStackTrace();
		}
		updateButtons();
	}

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			undoManager.undo();
		} catch (CannotRedoException cre) {
			cre.printStackTrace();
		}
		updateButtons();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// Save Button
		javax.swing.JScrollPane javax = (javax.swing.JScrollPane) jTabbedPane1
				.getSelectedComponent();
		javax.swing.JTextPane textpane = (javax.swing.JTextPane) javax
				.getViewport().getView();
		String text = textpane.getText();
		if (text.equals("")) {
			Message message = new Message("Error", "Empty file!");
			message.setVisible(true);
			return;
		}
		String path = null;
		if ((path = filenameMap.get(textpane)) != null) {
			saveFile(path, text);
			return;
		}
		JFileChooser fileChooser = new JFileChooser();
		FileNameExtensionFilter filter = new FileNameExtensionFilter(
				"SQL file", "sql");
		FileNameExtensionFilter filter1 = new FileNameExtensionFilter(
				"Text file", "txt");
		fileChooser.setFileFilter(filter1);
		fileChooser.setFileFilter(filter);
		fileChooser.setMultiSelectionEnabled(false);
		int ret = fileChooser.showSaveDialog(jButton2);
		if (ret == JFileChooser.APPROVE_OPTION) {

			String name = fileChooser.getSelectedFile().getName();
			path = fileChooser.getSelectedFile().getAbsolutePath();
			if (!name.toLowerCase().endsWith(".sql")
					&& !name.toLowerCase().endsWith(".txt")) {
				name += ".sql";
				path += ".sql";
			}
			if (saveFile(path, text) == 1) {
				filenameMap.put(textpane, path);
				jTabbedPane1.setTitleAt(jTabbedPane1.getSelectedIndex(), name);
			} else {
				Message a = new Message("Error",
						"Error occurred when saving file!");
				a.setVisible(true);
			}
		}
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		javax.swing.JScrollPane newScrollPane = new javax.swing.JScrollPane();
		javax.swing.JTextPane newTextPane = new javax.swing.JTextPane();
		newTextPane.getDocument().addUndoableEditListener(new UndoableEditListener() {
		    public void undoableEditHappened(UndoableEditEvent evt) {
		        undoManager.addEdit(evt.getEdit());
		    }
		});
		newScrollPane.setViewportView(newTextPane);
		String name = "Query " + (new Integer(queryNum++)).toString();
		jTabbedPane1.addTab(name, newScrollPane);
		jTabbedPane1.setSelectedComponent(newScrollPane);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		javax.swing.JScrollPane javax = (javax.swing.JScrollPane) jTabbedPane1
				.getSelectedComponent();
		javax.swing.JTextPane textpane = (javax.swing.JTextPane) javax
				.getViewport().getView();
		String text = textpane.getText();
		int pos = textpane.getCaretPosition();
		int start, end;
		text = text.replaceAll("\r\n", "\n");
		for (start = pos - 1; start >= 0; start--) {
			char c = text.charAt(start);
			if (text.charAt(start) == '\n')
				break;
		}
		for (end = pos; end != text.length(); end++) {
			if (text.charAt(end) == '\n')
				break;
		}
		text = text.substring(start + 1, end);
		ArrayList<Records> records = Main.main.excutePlan(text);
		String result = "";
		for (int i = 0; i < records.size(); i++) {
			if (records.get(i) != null)
				result += records.get(i).toString();
		}
		if (!result.equals("")) {
			jTextPane4.setText(result);
			jTabbedPane2.setSelectedIndex(1);
		}
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// Open Button
		JFileChooser fileChooser = new JFileChooser();
		FileNameExtensionFilter filter = new FileNameExtensionFilter(
				"SQL file", "sql");
		FileNameExtensionFilter filter1 = new FileNameExtensionFilter(
				"Text file", "txt");
		fileChooser.setFileFilter(filter1);
		fileChooser.setFileFilter(filter);
		fileChooser.setMultiSelectionEnabled(false);
		int ret = fileChooser.showOpenDialog(jButton3);
		if (ret == JFileChooser.APPROVE_OPTION) {
			javax.swing.JScrollPane newScrollPane = new javax.swing.JScrollPane();
			javax.swing.JTextPane newTextPane = new javax.swing.JTextPane();
			newScrollPane.setViewportView(newTextPane);
			String name = fileChooser.getSelectedFile().getName();
			String path = fileChooser.getSelectedFile().getAbsolutePath();
			String text = "";
			File file = new File(path);
			try {
				BufferedReader reader = new BufferedReader(new FileReader(file));
				String tmp = null;
				while ((tmp = reader.readLine()) != null) {
					text += tmp + "\r\n";
				}
				reader.close();
			} catch (FileNotFoundException e) {
				e.printStackTrace();
			} catch (IOException e) {
				e.printStackTrace();
			}
			newTextPane.setText(text);
			jTabbedPane1.addTab(name, newScrollPane);
			jTabbedPane1.setSelectedComponent(newScrollPane);
			filenameMap.put(newTextPane, path);
		}
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		javax.swing.JScrollPane javax = (javax.swing.JScrollPane) jTabbedPane1
				.getSelectedComponent();
		javax.swing.JTextPane textpane = (javax.swing.JTextPane) javax
				.getViewport().getView();
		String text = textpane.getText();
		ArrayList<Records> records = Main.main.excutePlan(text);
		boolean isFirst = true;;
		for (int i = 0; i < records.size(); i++) {
			if (records.get(i) != null && isFirst) {
				jTextPane4.setText(records.get(i).toString());
				jTabbedPane2.setSelectedIndex(1);
				isFirst = false;
			}
			else if(records.get(i) != null) {
				javax.swing.JScrollPane newScrollPane = new javax.swing.JScrollPane();
				javax.swing.JTextPane newTextPane = new javax.swing.JTextPane();
				newTextPane.setFont(new java.awt.Font("Courier New", 0, 12));
				newScrollPane.setViewportView(newTextPane);
				newTextPane.setText(records.get(i).toString());
				String name = "Result " + (new Integer(outputNum++)).toString();
				jTabbedPane2.addTab(name, newScrollPane);
			}
		}
	}

	private void updateButtons() {
		jButton10.setEnabled(undoManager.canUndo());
		jButton11.setEnabled(undoManager.canRedo());
		jMenuItem86.setEnabled(undoManager.canUndo());
		jMenuItem87.setEnabled(undoManager.canRedo());
	}

	private int saveFile(String path, String text) {
		PrintStream out = null;
		try {
			out = new PrintStream(new FileOutputStream(path), true);
			out.print(text);
			out.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
		return 1;
	}

	public void AppendOutput(String s) {
		jTextPane3.setText(jTextPane3.getText() + "\r\n" + s);
	}

	public void RefreshTree() {
		DefaultMutableTreeNode root = new DefaultMutableTreeNode("Database");
		DefaultMutableTreeNode tables = new DefaultMutableTreeNode("Tables");
		DefaultMutableTreeNode views = new DefaultMutableTreeNode("Views");
		Collection<String> collection = null;
		try {
			collection = Main.main.database.lsTable();
		} catch (IOException e) {
			System.err.println("database lsTable error.");
			e.printStackTrace();
		}
		Object[] a = collection.toArray();
		for (Object o : a) {
			DefaultMutableTreeNode node = new DefaultMutableTreeNode(
					o.toString());
			tables.add(node);
		}
		root.add(tables);
		try {
			collection = Main.main.database.lsView();
		} catch (IOException e) {
			System.err.println("database lsView error.");
			e.printStackTrace();
		}
		a = collection.toArray();
		for (Object o : a) {
			views.add(new DefaultMutableTreeNode(o.toString()));
		}
		root.add(views);
		DefaultTreeModel model = new DefaultTreeModel(root);
		jTree1.setModel(model);
	}

	private int queryNum = 2;
	private int outputNum = 2;
	protected UndoManager undoManager = new UndoManager();
	private Map<JTextPane, String> filenameMap = new HashMap<JTextPane, String>();
	private ErrorMsg.ErrorMsg errorMsg = null;
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JMenu jMenu21;
	private javax.swing.JMenu jMenu22;
	private javax.swing.JMenu jMenu23;
	private javax.swing.JMenu jMenu24;
	private javax.swing.JMenu jMenu25;
	private javax.swing.JMenuBar jMenuBar4;
	private javax.swing.JMenuItem jMenuItem100;
	private javax.swing.JMenuItem jMenuItem81;
	private javax.swing.JMenuItem jMenuItem82;
	private javax.swing.JMenuItem jMenuItem83;
	private javax.swing.JMenuItem jMenuItem84;
	private javax.swing.JMenuItem jMenuItem85;
	private javax.swing.JMenuItem jMenuItem86;
	private javax.swing.JMenuItem jMenuItem87;
	private javax.swing.JMenuItem jMenuItem88;
	private javax.swing.JMenuItem jMenuItem89;
	private javax.swing.JMenuItem jMenuItem90;
	private javax.swing.JMenuItem jMenuItem91;
	private javax.swing.JMenuItem jMenuItem92;
	private javax.swing.JMenuItem jMenuItem93;
	private javax.swing.JMenuItem jMenuItem94;
	private javax.swing.JMenuItem jMenuItem95;
	private javax.swing.JMenuItem jMenuItem96;
	private javax.swing.JMenuItem jMenuItem97;
	private javax.swing.JMenuItem jMenuItem98;
	private javax.swing.JMenuItem jMenuItem99;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JSeparator jSeparator17;
	private javax.swing.JSeparator jSeparator18;
	private javax.swing.JSeparator jSeparator19;
	private javax.swing.JSeparator jSeparator20;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTabbedPane jTabbedPane2;
	private javax.swing.JTextPane jTextPane1;
	private javax.swing.JTextPane jTextPane3;
	private javax.swing.JTextPane jTextPane4;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JToolBar jToolBar2;
	private javax.swing.JToolBar jToolBar3;
	private javax.swing.JToolBar jToolBar4;
	private javax.swing.JTree jTree1;
	// End of variables declaration//GEN-END:variables

}