
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Sep 02 00:33:17 CST 2011
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 73;
  public static final int LEFT = 56;
  public static final int FROM = 44;
  public static final int GT = 19;
  public static final int TIME = 89;
  public static final int TIMESTAMP = 90;
  public static final int GROUP = 46;
  public static final int NATURAL = 54;
  public static final int TIMEVAL = 5;
  public static final int RIGHT = 57;
  public static final int TABLE = 32;
  public static final int GE = 20;
  public static final int CROSS = 53;
  public static final int COMMA = 10;
  public static final int SUM = 78;
  public static final int INTVAL = 7;
  public static final int JOIN = 52;
  public static final int RPAREN = 13;
  public static final int ALL = 66;
  public static final int LT = 17;
  public static final int OROR = 24;
  public static final int DOUBLE = 87;
  public static final int LPAREN = 12;
  public static final int FALSE = 69;
  public static final int NOT = 62;
  public static final int DATEVAL = 4;
  public static final int LE = 18;
  public static final int VIEW = 33;
  public static final int MIN = 80;
  public static final int EQ = 15;
  public static final int INTO = 76;
  public static final int EXCEPT = 51;
  public static final int SELECT = 35;
  public static final int FULL = 55;
  public static final int TRUE = 68;
  public static final int ALTER = 27;
  public static final int PLUS = 21;
  public static final int DIVIDE = 23;
  public static final int INDEX = 34;
  public static final int ORDER = 47;
  public static final int UNION = 49;
  public static final int USE = 30;
  public static final int DELETE = 39;
  public static final int DECIMAL = 86;
  public static final int CHAR = 84;
  public static final int BOOLEAN = 82;
  public static final int STAR = 14;
  public static final int ADD = 28;
  public static final int MAX = 81;
  public static final int DOT = 9;
  public static final int INT = 83;
  public static final int AVG = 79;
  public static final int SHOW = 31;
  public static final int NULL = 67;
  public static final int EOF = 0;
  public static final int SEMICOLON = 11;
  public static final int BETWEEN = 59;
  public static final int INTERSECT = 50;
  public static final int WHERE = 45;
  public static final int DEFAULT = 43;
  public static final int COUNT = 77;
  public static final int IS = 74;
  public static final int MINUS = 22;
  public static final int DATE = 88;
  public static final int IN = 72;
  public static final int UNIQUE = 42;
  public static final int OR = 61;
  public static final int SET = 38;
  public static final int error = 1;
  public static final int ON = 71;
  public static final int DOUBLEVAL = 8;
  public static final int DESC = 48;
  public static final int ID = 2;
  public static final int BY = 75;
  public static final int DATABASE = 29;
  public static final int VALUES = 63;
  public static final int ANY = 65;
  public static final int CREATE = 25;
  public static final int TIMESTAMPVAL = 6;
  public static final int VARCHAR = 85;
  public static final int UNKNOWN = 70;
  public static final int UPDATE = 37;
  public static final int INSERT = 36;
  public static final int STRING = 3;
  public static final int NEQ = 16;
  public static final int PRIMARY = 40;
  public static final int AND = 60;
  public static final int DROP = 26;
  public static final int KEY = 41;
  public static final int HAVING = 58;
  public static final int DISTINCT = 64;
}

